name: Build and Publish
on:
  push:
    tags:
      # On standard release tags (e.g. "v29.0.12")
      - v[0-9]+.[0-9]+.[0-9]+
      # On release-candidate tags (e.g. "v1.2.3-rc.1")
      - v[0-9]+.[0-9]+.[0-9]+-rc.[0-9]+
jobs:
  publish:
    environment: jfrog-publish
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java: [11]
    name: Java ${{ matrix.java }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: ${{ matrix.java }}
          # Do NOT use caching, since we want to ensure published artifacts are fresh
      - run: ./.github/scripts/publish.sh
        env:
          JFROG_USER: ${{ secrets.JFROG_USER }}
          JFROG_KEY: ${{ secrets.JFROG_KEY }}
